version: "2"
services:
  next:
    container_name: next
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "300:300"
      - "3000:3000"
    tty: true
