name: Run build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  front_build:
    # 実行するインスタンス
    runs-on: ubuntu-latest
    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['16.x']
    # 各ステップの実行定義
    steps:
      # チェックアウト
      - uses: actions/checkout@v1

      # 使用するnodeのバージョンを指定
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # パッケージのインストール
      - name: yarn install
        run: yarn install

      # アプリのビルド
      - name: build
        run: yarn build
